// Generated by CoffeeScript 1.7.1
(function() {
  var fn, method, _console, _i, _len, _ref, _ref1;

  if (!(((_ref = window.localStorage) != null ? _ref.debug : void 0) === 'on' && window.console)) {
    _console = {};
    fn = function() {};
    _ref1 = 'assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn'.split(',');
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      method = _ref1[_i];
      _console[method] = fn;
    }
    window.console = _console;
  }

}).call(this);
