// Generated by CoffeeScript 1.10.0
(function() {
  var _console, fn, i, len, method, ref, ref1;

  if (!(((ref = window.localStorage) != null ? ref.debug : void 0) && window.console)) {
    _console = {};
    fn = function() {};
    ref1 = 'assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn,table'.split(',');
    for (i = 0, len = ref1.length; i < len; i++) {
      method = ref1[i];
      _console[method] = fn;
    }
    window.console = _console;
  }

}).call(this);
